/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajofinal;

/**
 *
 * @author Juliana
 */
public class VentPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentPrincipal
     */
    public VentPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        MnItForm = new javax.swing.JMenuItem();
        MnItSalir = new javax.swing.JMenuItem();
        MnAcerca = new javax.swing.JMenu();
        MnItAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dp.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        MnArchivo.setText("Archivo");

        MnItForm.setText("Form");
        MnItForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItFormActionPerformed(evt);
            }
        });
        MnArchivo.add(MnItForm);

        MnItSalir.setText("Salir");
        MnItSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItSalirActionPerformed(evt);
            }
        });
        MnArchivo.add(MnItSalir);

        jMenuBar1.add(MnArchivo);

        MnAcerca.setText("Acerca");

        MnItAcercade.setText("Acerca de");
        MnItAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItAcercadeActionPerformed(evt);
            }
        });
        MnAcerca.add(MnItAcercade);

        jMenuBar1.add(MnAcerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnItFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItFormActionPerformed
        frmFormulario form = new frmFormulario();
        dp.add(form);
        form.setClosable(true);
        form.setVisible(true);                                     
    }//GEN-LAST:event_MnItFormActionPerformed

    private void MnItSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_MnItSalirActionPerformed

    private void MnItAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItAcercadeActionPerformed
        frmAcercade acerca = new frmAcercade();
        dp.add(acerca);
        acerca.setClosable(true);
        acerca.setVisible(true);
    }//GEN-LAST:event_MnItAcercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnAcerca;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenuItem MnItAcercade;
    private javax.swing.JMenuItem MnItForm;
    private javax.swing.JMenuItem MnItSalir;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
